// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// A class that exposes all Firebase configuration for your app.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgLrPpx9TowdhgGVVbjCIk4irliybdKb8',
    appId: '1:15597410237:android:b54279e0e4926b1d5aa4d4',
    messagingSenderId: '15597410237',
    projectId: 'websmart-702de',
    databaseURL: 'https://websmart-702de-default-rtdb.firebaseio.com',
    storageBucket: 'websmart-702de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgLrPpx9TowdhgGVVbjCIk4irliybdKb8',
    appId: '1:15597410237:ios:cbd96cee1c20888b5aa4d4',
    messagingSenderId: '15597410237',
    projectId: 'websmart-702de',
    databaseURL: 'https://websmart-702de-default-rtdb.firebaseio.com',
    storageBucket: 'websmart-702de.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgLrPpx9TowdhgGVVbjCIk4irliybdKb8',
    appId: '1:15597410237:macos:cbd96cee1c20888b5aa4d4',
    messagingSenderId: '15597410237',
    projectId: 'websmart-702de',
    databaseURL: 'https://websmart-702de-default-rtdb.firebaseio.com',
    storageBucket: 'websmart-702de.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgLrPpx9TowdhgGVVbjCIk4irliybdKb8',
    appId: '1:15597410237:windows:cbd96cee1c20888b5aa4d4',
    messagingSenderId: '15597410237',
    projectId: 'websmart-702de',
    databaseURL: 'https://websmart-702de-default-rtdb.firebaseio.com',
    storageBucket: 'websmart-702de.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBgLrPpx9TowdhgGVVbjCIk4irliybdKb8',
    appId: '1:15597410237:linux:cbd96cee1c20888b5aa4d4',
    messagingSenderId: '15597410237',
    projectId: 'websmart-702de',
    databaseURL: 'https://websmart-702de-default-rtdb.firebaseio.com',
    storageBucket: 'websmart-702de.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgLrPpx9TowdhgGVVbjCIk4irliybdKb8',
    appId: '1:15597410237:web:cbd96cee1c20888b5aa4d4',
    messagingSenderId: '15597410237',
    projectId: 'websmart-702de',
    authDomain: 'websmart-702de.firebaseapp.com',
    databaseURL: 'https://websmart-702de-default-rtdb.firebaseio.com',
    storageBucket: 'websmart-702de.firebasestorage.app',
  );
}
